const MY_SUMMONER_ID = "CZOat495FA0y8NTzHarUXKpstuutCO4nV6G1lF-OZJPy0MA";
const MY_SUMMONER_NAME = "gabdez";
const API_KEY = "RGAPI-32ceb2d7-44d2-4129-bc50-07daed1d7c8a";
const ACCOUNT_ID = "eflt0vXyJEkN5IUKAfTi51VGhbmsseojvR-O251Ct9Uvxbk";

export default {
  MY_SUMMONER_ID: MY_SUMMONER_ID,
  MY_SUMMONER_NAME: MY_SUMMONER_NAME,
  API_KEY: API_KEY,
  ACCOUNT_ID: ACCOUNT_ID
};
