const MY_SUMMONER_ID = "CZOat495FA0y8NTzHarUXKpstuutCO4nV6G1lF-OZJPy0MA";
const MY_SUMMONER_NAME = "gabdez";
const API_KEY = "RGAPI-f0b2ac1e-b626-4ff5-8231-6cde66e58e92";
const ACCOUNT_ID = "eflt0vXyJEkN5IUKAfTi51VGhbmsseojvR-O251Ct9Uvxbk";
//mdp : Lbjcavs00&

export default {
  MY_SUMMONER_ID: MY_SUMMONER_ID,
  MY_SUMMONER_NAME: MY_SUMMONER_NAME,
  API_KEY: API_KEY,
  ACCOUNT_ID: ACCOUNT_ID
};
