const MY_SUMMONER_ID = "CZOat495FA0y8NTzHarUXKpstuutCO4nV6G1lF-OZJPy0MA";
const MY_SUMMONER_NAME = "gabdez";
const API_KEY = "RGAPI-0acd1db5-c21b-4c95-ba9d-80e0146ae53c";

export default {
  MY_SUMMONER_ID: MY_SUMMONER_ID,
  MY_SUMMONER_NAME: MY_SUMMONER_NAME,
  API_KEY: API_KEY
};
